version: "2.4"
volumes:
  persistent-volume: {}
services:
  runner:
    image: ghcr.io/product-os/self-hosted-runners:v0.0.3
    privileged: true
    userns_mode: host
    cap_add:
      - ALL
    healthcheck:
      test: >
        /bin/bash -c '[[ -e /var/run/docker.sock ]] \
          && (curl --silent --fail --unix-socket /var/run/docker.sock http:/v1.40/_ping \
          && pgrep Runner.Listener) || true'
      interval: 300s
      timeout: 60s
      retries: 5
    env_file:
      - .env
    environment:
      GITHUB_ENTERPRISE: balena
    volumes:
      - persistent-volume:/home/githhub/_work
      - persistent-volume:/var/lib/docker
      - persistent-volume:/scratch
      - persistent-volume:/balena
    restart: unless-stopped
