---
version: '2.1'

volumes:
  persistent-volume: {}

services:
  github-actions-runner:
    build: runner
    privileged: true
    userns_mode: host
    cap_add:
      - ALL
    healthcheck:
      test: |
        /bin/bash -c '[[ -e /var/run/docker.sock ]] \
          && (curl --silent --fail --unix-socket /var/run/docker.sock http:/v1.40/_ping \
          && pgrep Runner.Listener) || true'
      interval: 300s
      timeout: 60s
      retries: 5
    volumes:
      - persistent-volume:/home/githhub/_work
      - persistent-volume:/var/lib/docker
      - persistent-volume:/scratch
      - persistent-volume:/balena
    restart: unless-stopped
