#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2310,SC2312

set -euo pipefail

. /etc/s6-overlay/scripts/functions

truthy "${VERBOSE:-}" && set -x

sysctl -w user.max_user_namespaces=15000 || true

rm -f /var/run/docker.pid

dockerd_args=()

if [[ -n "${EXTRA_DOCKERD_ARGS:-}" ]]; then
  # split the string into an array
  read -r -a extra_args <<<"${EXTRA_DOCKERD_ARGS}"
fi

dockerd_args+=("${extra_args[@]}")

mount -t cgroup cgroup /sys/fs/cgroup || true
update-alternatives --set iptables /usr/sbin/iptables-legacy || true

echo "Starting dockerd with extra args: ${dockerd_args[*]}"
jq . /etc/docker/daemon.json

# reset the environment and execute dockerd
# https://docs.docker.com/reference/cli/dockerd/#environment-variables
exec env -i \
  PATH="${PATH}" \
  DOCKER_CERT_PATH="${DOCKER_CERT_PATH:-}" \
  DOCKER_DRIVER="${DOCKER_DRIVER:-}" \
  DOCKER_RAMDISK="${DOCKER_RAMDISK:-}" \
  DOCKER_TLS_VERIFY="${DOCKER_TLS_VERIFY:-}" \
  HTTP_PROXY="${HTTP_PROXY:-}" \
  HTTPS_PROXY="${HTTPS_PROXY:-}" \
  MOBY_DISABLE_PIGZ="${MOBY_DISABLE_PIGZ:-}" \
  NO_PROXY="${NO_PROXY:-}" \
  dockerd --config-file /etc/docker/daemon.json "${dockerd_args[@]}" 2>&1
