#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2310,SC2312

set -euo pipefail

. /etc/s6-overlay/scripts/functions

truthy "${VERBOSE:-}" && set -x

INSECURE_REGISTRY=${INSECURE_REGISTRY:-""}
DOCKER_REGISTRY_MIRROR=${DOCKER_REGISTRY_MIRROR:-""}
MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-3}
MAX_CONCURRENT_UPLOADS=${MAX_CONCURRENT_UPLOADS:-5}

sysctl -w user.max_user_namespaces=15000 || true

rm -f /var/run/docker.pid

dockerd_args=()
dockerd_args+=("--data-root=/scratch/docker")
dockerd_args+=("--mtu=$(cat /sys/class/net/"$(ip route get 8.8.8.8 | awk '{ print $5 }')"/mtu)")
dockerd_args+=("--max-concurrent-downloads=${MAX_CONCURRENT_DOWNLOADS}")
dockerd_args+=("--max-concurrent-uploads=${MAX_CONCURRENT_UPLOADS}")

for registry in ${INSECURE_REGISTRY}; do
  dockerd_args+=("--insecure-registry=${registry}")
done

if [[ -n "${DOCKER_REGISTRY_MIRROR}" ]]; then
  dockerd_args+=("--registry-mirror=${DOCKER_REGISTRY_MIRROR}")
fi

if [[ -n "${EXTRA_DOCKERD_ARGS:-}" ]]; then
  # split the string into an array
  read -r -a extra_args <<<"${EXTRA_DOCKERD_ARGS}"
fi

dockerd_args+=("${extra_args[@]}")

mount -t cgroup cgroup /sys/fs/cgroup || true
update-alternatives --set iptables /usr/sbin/iptables-legacy || true

# reset the environment and execute dockerd
exec env -i PATH="${PATH}" dockerd "${dockerd_args[@]}" 2>&1
