# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true

["mikefarah/yq"]
tag = "v4.30.7"
asset_filters = [".tar.gz"]
target = "/usr/local/bin/yq"
verify_sha256 = "5910801c24cf275b75768b0c05e95f2e3f25fcd0ed1172790bb9920f1b0f3477"
file = "yq_*"
all = false

["powershell/powershell"]
asset_filters = ["powershell", "^fxdependent", "^alpine", ".tar.gz"]
tag = "v${POWERSHELL_VERSION}"
target = "/opt/microsoft/powershell/7"
file = "*"

["actions/runner"]
asset_filters = ["^noexternals", "^noruntime", ".tar.gz"]
tag = "${ACTIONS_RUNNER_VERSION}"
target = "./"
file = "*"

["actions/runner-container-hooks"]
asset_filters = ["docker", ".zip"]
tag = "v${ACTIONS_HOOKS_VERSION}"
target = "./docker/"
file = "*"

["https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz"]
target = "/usr/"
file = "node-v${NODE_VERSION}-linux-x64/*"

["https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz"]
target = "/"
file = "*"

["https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz"]
target = "/"
file = "*"

["balena-io/balena-cli"]
asset_filters = ["linux", "x64", "standalone", ".zip"]
tag = "${BALENA_CLI_VERSION}"
target = "/usr/local/lib/balena-cli/"
file = "*"
