# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true
system = "linux/arm64"

["mikefarah/yq"]
tag = "v4.30.7"
asset_filters = [".tar.gz"]
target = "/usr/local/bin/yq"
file = "yq_*"
all = false

["powershell/powershell"]
asset_filters = ["powershell", "^fxdependent", "^musl", ".tar.gz"]
target = "/opt/microsoft/powershell/7"
file = "*"

["actions/runner"]
asset_filters = ["^noexternals", "^noruntime", ".tar.gz"]
target = "./"
file = "*"

["actions/runner-container-hooks"]
asset_filters = ["docker", ".zip"]
target = "./docker/"
file = "*"

["just-containers/s6-overlay"]
target = "/"
file = "*"

["balena-io/balena-cli"]
asset_filters = ["standalone", ".zip"]
target = "/usr/local/lib/balena-cli/"
file = "*"
