#!/usr/bin/env bash

# Exit if script is executed, not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This script must be sourced, not executed."
    exit 1
fi

curl_with_opts() {
    curl --fail --silent --retry 3 --connect-timeout 3 "$@"
}

truthy() {
    [[ ${1,,} =~ true|yes|on|1 ]]
}

get_geo() {
    # shellcheck disable=SC2310
    if curl_with_opts -I https://ipinfo.io >/dev/null 2>&1; then
        geoip_api_url=https://ipinfo.io
        if [[ -n ${GEOIP_API_TOKEN:-} ]]; then
            geoip_api_url="${geoip_api_url}?token=${GEOIP_API_TOKEN}"
        fi
        curl_with_opts "${geoip_api_url}"
    fi
}
