#!/usr/bin/env bash

# Get a GitHub authentication token for the runner either via GitHub App or PAT
# and write it to /tmp/gh_token

set -euo pipefail

# force debug tracing to off as we are dealing with secrets
set +x

get_installation_token() {
    if [ -n "${GITHUB_ENTERPRISE:-}" ]; then
        # this endpoint does not work with GitHub Enterprise as no such permission exists for GitHub Apps
        echo "GitHub Apps are not a supported authentication method for GitHub Enterprise runners"
        return
    fi

    # https://www.npmjs.com/package/github-app-installation-token
    # https://github.com/gagoar/github-app-installation-token
    echo "Requesting installation token..."
    github-app-installation-token \
        --appId "${ACTIONS_RUNNER_APP_ID}" \
        --installationId "${ACTIONS_RUNNER_INSTALLATION_ID}" \
        --privateKeyLocation /tmp/private.pem 2>/dev/null | tail -n1 >/tmp/gh_token

    # cleanup secret files
    rm -f /tmp/private.pem

    echo "Token has been written to /tmp/gh_token"
}

if [ -n "${ACTIONS_RUNNER_APP_KEY_B64:-}" ]; then
    echo "${ACTIONS_RUNNER_APP_KEY_B64}" | base64 -d >"/tmp/private.pem" || true
fi

if [ -f "/tmp/private.pem" ] && [ -n "${ACTIONS_RUNNER_APP_ID:-}" ] && [ -n "${ACTIONS_RUNNER_INSTALLATION_ID:-}" ]; then
    get_installation_token
    exit 0
fi

ACTIONS_RUNNER_AUTH_TOKEN="${ACTIONS_RUNNER_AUTH_TOKEN:-}"

if [ -z "${ACTIONS_RUNNER_AUTH_TOKEN:-}" ]; then
    ACTIONS_RUNNER_AUTH_TOKEN="${GH_TOKEN:-}"
fi

if [ -z "${ACTIONS_RUNNER_AUTH_TOKEN:-}" ]; then
    ACTIONS_RUNNER_AUTH_TOKEN="${GITHUB_TOKEN:-}"
fi

if [ -z "${ACTIONS_RUNNER_AUTH_TOKEN:-}" ]; then
    echo "ACTIONS_RUNNER_AUTH_TOKEN is unset"
    exit 1
fi

echo "${ACTIONS_RUNNER_AUTH_TOKEN}" >/tmp/gh_token

echo "Token has been written to /tmp/gh_token"
exit 0
