#!/usr/bin/env bash

set -euo pipefail

# Check if the runner is healthy

while ! docker info 1>/dev/null 2>&1; do
    echo "Waiting for docker to be ready"
    sleep 1
done

docker info

docker run hello-world

docker buildx create --name builder-debug --driver docker-container --driver-opt network=host --buildkitd-flags "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host" --use

docker create --name builder-debug-container --privileged moby/buildkit:buildx-stable-1

docker inspect builder-debug-container

find / -name buildctl

docker buildx inspect --bootstrap --builder builder-debug
