#!/usr/bin/env bash

set -ae

[[ $VERBOSE =~ true|True|yes|Yes|on|On|1 ]] && set -x

# these tmpfs mounts need the executable bit set
mount -o remount,rw,exec tmpfs /tmp
mount -o remount,rw,exec tmpfs /run

function mount_as_tmpfs() {
    # unmount any existing binds
    umount "${1}" 2>/dev/null || true
    # create mountpoint for a new tmpfs
    mkdir -p "${1}.tmpfs"
    # create the tmpfs with execute permissions
    mount -t tmpfs -o rw,exec tmpfs "${1}.tmpfs"
    # copy the contents of the original directory to the tmpfs
    cp -a "${1}"/* "${1}.tmpfs"
    # bind mount the tmpfs over the original
    mount --bind "${1}.tmpfs" "${1}"
}

# create tmpfs overlays for some directories that need to be writable
# but should not persist container restarts
for dir in /home/runner /opt; do
    mount_as_tmpfs "${dir}" || true
done
