#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2310,SC2312

# Get a GitHub authentication token for the runner either via GitHub App or PAT

set -euo pipefail

# required to use `read` with pipes
shopt -s lastpipe

# force debug tracing to off as we are dealing with secrets
set +x

curl_with_opts() {
    curl --fail --silent --retry 3 --connect-timeout 3 "$@"
}

truthy() {
    [[ ${1,,} =~ true|yes|on|1 ]]
}

get_geo() {
    local _geoip_api_url
    if curl_with_opts -I https://ipinfo.io >/dev/null 2>&1; then
        _geoip_api_url=https://ipinfo.io
        if [[ -n ${GEOIP_API_TOKEN:-} ]]; then
            _geoip_api_url="${_geoip_api_url}?token=${GEOIP_API_TOKEN}"
        fi
        curl_with_opts -L "${_geoip_api_url}"
    fi
}

get_app_token() {
    local _app_id="${1}"
    local _installation_id="${2}"
    local _private_key_file="${3}"
    local _registration_slug="${4}"

    if [[ "${_registration_slug:-}" =~ ^enterprises\/.*$ ]]; then
        warn "GitHub Apps are not a supported authentication method for GitHub Enterprise runners"
        return 1
    fi

    if [[ -n "${_app_id}" ]]; then
        info "Using GitHub App ID: ${_app_id}"
    else
        warn "GitHub App ID not provided!"
        return 1
    fi

    if [[ -n "${_installation_id}" ]]; then
        info "Using GitHub App Installation ID: ${_installation_id}"
    else
        warn "GitHub App Installation ID not provided!"
        return 1
    fi

    if [[ -n "${_private_key_file}" ]]; then
        info "Using GitHub App Private Key File: ${_private_key_file}"
    else
        warn "GitHub App Private Key File not provided!"
        return 1
    fi

    info "Requesting installation token from GitHub App..."

    # https://github.com/nabeken/go-github-apps
    GITHUB_PRIV_KEY=$(<"${_private_key_file}")
    export GITHUB_PRIV_KEY
    eval "$(go-github-apps -export -app-id "${_app_id}" -inst-id "${_installation_id}" || exit 1)"

    info "GitHub App token has been exported to GITHUB_TOKEN environment variable."

    unset GITHUB_PRIV_KEY
    rm -f "${_private_key_file}"
}

# https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runner-groups?apiVersion=2022-11-28#list-self-hosted-runner-groups-for-an-enterprise
# https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runner-groups?apiVersion=2022-11-28#list-self-hosted-runner-groups-for-an-organization
get_runner_group_id() {
    local _registration_slug="${1}"
    local _runner_group_name="${2}"
    local _github_token="${3}"
    local _api_url="https://api.github.com/${_registration_slug}/actions/runner-groups"

    info "Getting runner group ID from GitHub..."
    (curl --fail-with-body --location "${_api_url}" -H "Authorization: token ${_github_token}") |
        jq --arg name "${_runner_group_name}" '.runner_groups[] | select(.name == $name) | .id'
}

check_token_limit() {
    local _github_token="${1}"
	local _api_url="https://api.github.com/rate_limit"

	local _json
	local _used
	local _limit
	local _remaining
	local _reset
	local _now
	local _datetime
	local _minutes

	_json="$(curl_with_opts "${_api_url}" -H "Authorization: token ${_github_token}")"
	_used="$(echo "${_json}" | jq -re .rate.used)"
	_limit="$(echo "${_json}" | jq -re .rate.limit)"
	_remaining="$(echo "${_json}" | jq -re .rate.remaining)"
	_reset="$(echo "${_json}" | jq -re .rate.reset)"
	_now=$(date +%s)
	_datetime="$(date -d @"$(echo "${_json}" | jq -re .rate.reset)" +"%Y-%m-%d %H:%M:%S")"
	_minutes="$(( (_reset - _now) / 60 ))m"

	info "GitHub token used ${_used}/${_limit}, resetting in ${_minutes} (${_datetime})."
	if [[ -n "${_remaining:-}" ]] && [[ ${_remaining:-} -le 0 ]]; then
		warn "All GitHub token quota used, runner registration will fail until reset."
	fi
}

# Create a just-in-time runner for the repository, organization, or enterprise
# https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-an-enterprise
# https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-an-organization
# https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-a-repository
register_runner() {
    local _registration_slug="${1}"
    local _github_token="${2}"
    local _json_payload="${3}"
    local _api_url="https://api.github.com/${_registration_slug}/actions/runners/generate-jitconfig"

    check_token_limit "${_github_token}"

    info "Registering runner with GitHub..."
    (curl --fail-with-body --location --request POST "${_api_url}" -H "Authorization: token ${_github_token}" \
        -d "${_json_payload}")
}

log() {
    _level="$1"
    _message="$2"
    printf "[%s][%s] %s\n" "${0}" "${_level}" "${_message}" >&2
}

fail() {
    error "$1"
    sleep 10
    exit 1
}

error() {
    log "ERROR" "$1"
}

warn() {
    log "WARN" "$1"
}

info() {
    log "INFO" "$1"
}

cleanup() {
    info "cleaning up..."
    rm -f /tmp/private.pem
}

# Default labels for the runner, these would otherwise be set by config.sh
# Returns a space-separated list of labels
get_default_labels() {
    local _labels=()

    _labels+=("self-hosted")
    _labels+=("Linux")

    case $(uname -m) in
    x86_64) _labels+=("X64") ;;
    aarch64) _labels+=("ARM64") ;;
    *) fail "Unsupported architecture: $(uname -m)" ;;
    esac

    printf '%s ' "${_labels[@]}"
}

# Labels are used to filter runner jobs
get_runner_labels_json() {

    local _runner_labels=()

    local _default_labels=()
    local _build_labels=()
    local _runtime_labels=()
    local _extra_labels=()

    read -r -a _default_labels < <(get_default_labels)

    # shellcheck disable=SC2086
    read -r -a _build_labels <<<"$(printf '%s ' ${ACTIONS_RUNNER_BUILD_LABELS:-})"

    # shellcheck disable=SC2086
    read -r -a _runtime_labels <<<"$(printf '%s ' ${ACTIONS_RUNNER_RUNTIME_LABELS:-})"

    # shellcheck disable=SC2086
    read -r -a _extra_labels <<<"$(printf '%s ' ${ACTIONS_RUNNER_EXTRA_LABELS:-})"

    # Allow the user to disable default labels
    truthy "${ACTIONS_RUNNER_NO_DEFAULT_LABELS:-}" ||  _runner_labels+=("${_default_labels[@]}")
    # Allow the user to disable build labels
    truthy "${ACTIONS_RUNNER_NO_AUTOMATIC_LABELS:-}" || truthy "${ACTIONS_RUNNER_NO_BUILD_LABELS:-}" || _runner_labels+=("${_build_labels[@]}")
    # Allow the user to disable runtime labels
    truthy "${ACTIONS_RUNNER_NO_AUTOMATIC_LABELS:-}" || truthy "${ACTIONS_RUNNER_NO_RUNTIME_LABELS:-}" || _runner_labels+=("${_runtime_labels[@]}")
    # Add any extra labels
    _runner_labels+=("${_extra_labels[@]}")

    # Format as JSON array
    printf '%s\n' "${_runner_labels[@]}" | jq -R . | jq -s .
}

trap cleanup EXIT

truthy "${VERBOSE:-}" && set -x

registration_slug="${ACTIONS_RUNNER_REGISTRATION_SLUG:-}"
runner_name="${ACTIONS_RUNNER_NAME:-$(uuidgen)}"
runner_work_folder="${ACTIONS_RUNNER_WORK_DIRECTORY:-"/home/runner/_work"}"
# This is the default runner group for repositories, organizations, and enterprises
runner_group_name="${ACTIONS_RUNNER_GROUP:-"Default"}"
runner_group_id="1"

app_id="${ACTIONS_RUNNER_APP_ID:-}"
installation_id="${ACTIONS_RUNNER_INSTALLATION_ID:-}"
private_key_file="${ACTIONS_RUNNER_PRIVATE_KEY_FILE:-"/tmp/private.pem"}"
private_key_base64="${ACTIONS_RUNNER_APP_KEY_B64:-}"

runner_config_file="${1:-"/home/runner/.jitconfig"}"
runner_id_file="${2:-"/home/runner/.id"}"

if [[ -f "${runner_config_file}" ]]; then
    info "Runner is already registered, skipping..."
    exit 0
fi

runner_labels_json="$(get_runner_labels_json)"

if truthy "${DRY_RUN:-}"; then
    info "Dry run enabled, exiting..."
    exit 0
fi

if [[ ! "${registration_slug:-}" =~ ^(repos|orgs|enterprises)\/.*$ ]]; then
    fail "ACTIONS_RUNNER_REGISTRATION_SLUG must be in the format repos/OWNER/REPO or orgs/ORG or enterprises/ENTERPRISE"
fi

for key in ACTIONS_RUNNER_AUTH_TOKEN GITHUB_TOKEN GH_TOKEN; do
    if [[ -n "${!key:-}" ]]; then
        info "Using '${key}' for authentication..."
        github_token="${!key}"
        break
    fi
done

if [[ -z "${github_token:-}" ]]; then
    # decode app key and write to a file if one was provided via env vars
    if [[ ! -f "${private_key_file}" ]] && [[ -n "${private_key_base64}" ]]; then
        echo "${private_key_base64}" | base64 -d >"${private_key_file}" || true
    fi

    get_app_token "${app_id}" "${installation_id}" "${private_key_file}" "${registration_slug}" || true
    github_token="${GITHUB_TOKEN:-}"
fi

if [[ -z "${github_token:-}" ]]; then
    fail "No authentication methods provided!"
fi

# Runner groups are only available for organizations and enterprises
if [[ ! "${registration_slug:-}" =~ ^repos\/.*$ ]]; then
    runner_group_id="$(get_runner_group_id "${registration_slug}" "${runner_group_name}" "${github_token}")"
fi

# Use jq to construct the JSON object
json_payload=$(jq -nc \
    --arg name "${runner_name}" \
    --argjson runner_group_id "${runner_group_id}" \
    --argjson labels "${runner_labels_json}" \
    --arg work_folder "${runner_work_folder}" \
    '{name: $name, runner_group_id: $runner_group_id, labels: $labels, work_folder: $work_folder}')

jq . <<<"${json_payload}"

json_response=$(register_runner "${registration_slug}" "${github_token}" "${json_payload}")

# write jit config
echo "${json_response}" | jq -r '.encoded_jit_config' > "${runner_config_file}"

# write id that will be used for teardown
echo "${json_response}" | jq -r '.runner.id' > "${runner_id_file}"

info "Runner configuration written to ${runner_config_file}."
