#!/usr/bin/env bash

set -ae

[[ $VERBOSE =~ true|True|yes|Yes|on|On|1 ]] && set -x

case "$(uname -m)-$(dpkg --print-architecture)" in
aarch64-armhf)
    # setarch for aarch64 kernel running armhf userspace
    exec /usr/bin/setarch linux32 "${@}"
    ;;
*)
    exec "${@}"
    ;;
esac
