#!/usr/bin/env bash

set -ae

[[ $VERBOSE =~ true|True|yes|Yes|on|On|1 ]] && set -x

ACTIONS_RUNNER_MACHINE_NAME=${ACTIONS_RUNNER_MACHINE_NAME:-$(hostname)}

function set_hostname() {

    if [ "${ACTIONS_RUNNER_MACHINE_NAME}" = "$(hostname)" ]; then
        return
    fi

    echo "${ACTIONS_RUNNER_MACHINE_NAME}" > /etc/hostname
    # sed "s/127.0.1.1.*/127.0.1.1 ${new_hostname}/" -i /etc/hosts
    hostname -F /etc/hostname
    hostname
}

set_hostname
