#!/usr/bin/env bash

if [ -s "/var/run/runner.token" ]; then
  su - runner -c "/home/runner/config.sh remove --token $(</var/run/runner.token)"
fi

rm -f /var/run/runner.token
rm -f /home/runner/.runner

echo "$1" >/run/s6-linux-init-container-results/exitcode
/run/s6/basedir/bin/halt
