#!/usr/bin/env bash

# make sure we've cleaned up our environment of secrets
rm -f /var/envrionment
rm -f /var/variables
rm -f /var/secrets
rm -f /run/runner.token

# run as runner user in a clean environment without secrets
exec su - runner -c "/home/runner/run.sh" 2>&1
