#!/usr/bin/env bash

set -ae

[[ $VERBOSE =~ true|True|yes|Yes|on|On|1 ]] && set -x

ACTIONS_RUNNER_NAME=${ACTIONS_RUNNER_NAME:-$(uuidgen)}
# Configure the runner to only take one job and then let the service un-configure the runner after the job finishes (default false)
ACTIONS_RUNNER_EPHEMERAL=${ACTIONS_RUNNER_EPHEMERAL:-true}
# Replace any existing runner with the same name (default false)
ACTIONS_RUNNER_REPLACE=${ACTIONS_RUNNER_REPLACE:-false}
ACTIONS_RUNNER_GROUP=${ACTIONS_RUNNER_GROUP:-Default}
ACTIONS_RUNNER_WORK_DIRECTORY=${ACTIONS_RUNNER_WORK_DIRECTORY:-/home/runner/_work}
GITHUB_ORG=${GITHUB_ORG:-balena-io}

curl_with_opts() {
    curl --fail --silent --retry 3 --connect-timeout 3 "$@"
}

get_geo() {
    if curl_with_opts -I https://ipinfo.io; then
        geoip_api_url=https://ipinfo.io
        if [[ -n $GEOIP_API_TOKEN ]]; then
            geoip_api_url="${geoip_api_url}?token=${GEOIP_API_TOKEN}"
        fi
        ipinfo="$(curl_with_opts "${geoip_api_url}")"
    else
        ipinfo='{"city":"Unknown","region":"Unknown","country":"Unknown"}'
    fi
}

get_geo

echo "${ipinfo}" | jq

runner_tags=()
runner_tags+=("family:$(cat </etc/lsb-release | grep DISTRIB_ID | awk -F'=' '{print $2}')")
runner_tags+=("distro:$(cat </etc/lsb-release | grep DISTRIB_CODENAME | awk -F'=' '{print $2}' | sed 's/"//g')")
runner_tags+=("major:$(cat </etc/lsb-release | grep DISTRIB_RELEASE | awk -F'=' '{print $2}' | sed 's/"//g')")
runner_tags+=("minor:$(cat </etc/lsb-release | grep DISTRIB_DESCRIPTION | awk -F'=' '{print $2}' | sed 's/"//g')")
runner_tags+=("machine:$(uname -m)")
runner_tags+=("arch:$(dpkg --print-architecture)")
runner_tags+=("board:$(cat </sys/devices/virtual/dmi/id/board_name || echo 'unknown')")
runner_tags+=("cpu:$(nproc)")
runner_tags+=("mem:$(($(cat </proc/meminfo | grep MemTotal | awk '{print $2}') / 1024 / 1024))Gi")
runner_tags+=("country:$(echo "${ipinfo}" | jq -r .country | tr ' ' '_' | tr '[:upper:]' '[:lower:]')")
runner_tags+=("region:$(echo "${ipinfo}" | jq -r .region | tr ' ' '_' | tr '[:upper:]' '[:lower:]')")
runner_tags+=("city:$(echo "${ipinfo}" | jq -r .city | tr ' ' '_' | tr '[:upper:]' '[:lower:]')")
runner_tags+=("platform:${ACTIONS_RUNNER_PLATFORM}")
runner_tags+=("balena_device_uuid:${BALENA_DEVICE_UUID:-unknown}")

if [[ -n $ACTIONS_RUNNER_EXTRA_TAGS ]]; then
    runner_tags+=("${ACTIONS_RUNNER_EXTRA_TAGS}")
fi

# Join the array elements with commas
runner_tags_str=$(printf "%s," "${runner_tags[@]}")
# Remove the trailing comma
runner_tags_str=${runner_tags_str%,}

slug=orgs
url="https://github.com/${GITHUB_ORG}"
if [[ -n "${GITHUB_ENTERPRISE}" ]]; then
    GITHUB_ORG="${GITHUB_ENTERPRISE}"
    slug=enterprises
    url="https://github.com/${slug}/${GITHUB_ENTERPRISE}"
fi

# https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization
registration_url="https://api.github.com/${slug}/${GITHUB_ORG}/actions/runners/registration-token"
echo "Requesting registration token..."
payload=$(curl_with_opts -sX POST "${registration_url}" -H "Authorization: token $(</tmp/gh_token)") || {
    echo "Failed to get registration token from ${registration_url}"
    exit 1
}
runner_token="$(echo "${payload}" | jq -r .token)"

# remove token created by /etc/s6-overlay/scripts/mount-tmpfs
rm -f /tmp/gh_token

# write token to file to be read during teardown
echo "${runner_token}" >"/var/run/runner.token"

config_args=()
config_args+=("--disableupdate")
config_args+=("--unattended")
config_args+=("--name" "${ACTIONS_RUNNER_NAME}")
config_args+=("--token" "${runner_token}")
config_args+=("--url" "${url}")
config_args+=("--runnergroup" "${ACTIONS_RUNNER_GROUP}")
config_args+=("--work" "${ACTIONS_RUNNER_WORK_DIRECTORY}")
config_args+=("--labels" "\"${runner_tags_str}\"")

[[ ${ACTIONS_RUNNER_EPHEMERAL} =~ true|True|1|yes|Yes ]] && config_args+=("--ephemeral")
[[ ${ACTIONS_RUNNER_REPLACE} =~ true|True|1|yes|Yes ]] && config_args+=("--replace")

# create and chown the work directory
mkdir -p "${ACTIONS_RUNNER_WORK_DIRECTORY}"
chown -R "runner:runner" "${ACTIONS_RUNNER_WORK_DIRECTORY}"

# chown the current directory since files will be written by the runner process
chown -R "runner:runner" /home/runner/

# remove any existing runner registration files
rm -f /home/runner/.runner

# configure as runner user
su - runner -c "/home/runner/config.sh ${config_args[*]}" 2>&1

# run as runner user
exec su - runner -c "/home/runner/run.sh" 2>&1
