# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true

["mikefarah/yq"]
tag = "v4.30.7"
asset_filters = [".tar.gz"]
target = "/usr/local/bin/yq"
verify_sha256 = "6fb63d8a57e0e88da403dc2c7310abddba7835b1930a213a489742ea5d743418"
file = "yq_*"
all = false

["powershell/powershell"]
asset_filters = ["powershell", "^fxdependent", "^alpine", ".tar.gz"]
tag = "v7.3.2"
target = "/opt/microsoft/powershell/7/"
verify_sha256 = "cdb0f04db328bc6230cbcfcc04db11a20111bc58637468aad79d56a832c489d4"
file = "*"

["actions/runner"]
asset_filters = ["^noexternals", "^noruntime", ".tar.gz"]
tag = "v2.303.0"
target = "./"
verify_sha256 = "cb55db5f6e8e2ab3db0c4236aad7d240e413a2b8aa7dffd24a288255dbb05fcf"
file = "*"

["actions/runner-container-hooks"]
asset_filters = ["docker", ".zip"]
tag = "v0.3.1"
target = "./docker/"
verify_sha256 = "93e1f85b6986181e89c08c38605d11d2e3e37a990ad388e0401c872609bfcc69"
file = "*"

["https://nodejs.org/dist/v18.14.2/node-v18.14.2-linux-armv7l.tar.xz"]
target = "/usr/"
verify_sha256 = "39c308b9a75591860c4d2c05edae82c10a1157cfb67594837d60666ee960e8fe"
file = "node-v18.14.2-linux-armv7l/*"

["https://github.com/just-containers/s6-overlay/releases/download/v3.1.4.2/s6-overlay-noarch.tar.xz"]
verify_sha256 = "d63a4b00051127ae66992164926d5772faee2bb598c666898184879b3ff403fc"
target = "/"
file = "*"

["https://github.com/just-containers/s6-overlay/releases/download/v3.1.4.2/s6-overlay-arm.tar.xz"]
verify_sha256 = "8f00319864d84640ce881dcece946c5584f19bc53ce132be7fb4ee2dbc1905ba"
target = "/"
file = "*"
