version: "2.4"

services:
  # default to VM runner target
  runner:
    build: .
    privileged: true
    network_mode: host
    tmpfs:
      - /tmp
      - /run
      - /srv
      - /scratch
    # see README for more environment variables
    env_file:
      - .env
    environment:
      VERBOSE: "true"
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: 50000
      GITHUB_ORG: product-os
      ACTIONS_RUNNER_GROUP: runners-under-test
      ACTIONS_RUNNER_EXTRA_TAGS: commit:${GITHUB_SHA:-dev}
      ACTIONS_RUNNER_NO_DEFAULT_LABELS: true
