version: "2.4"

services:
  sut:
    extends:
      file: docker-compose.yml
      service: runner
    image: sut
    # see README for more environment variables
    env_file:
      - .env
    environment:
      VERBOSE: ${VERBOSE:-true}
      ACTIONS_RUNNER_REGISTRATION_SLUG: repos/product-os/self-hosted-runners
      ACTIONS_RUNNER_EXTRA_LABELS: run_id:${GITHUB_RUN_ID:-dev}
      ACTIONS_RUNNER_NO_DEFAULT_LABELS: true
