version: "2.4"

services:
  # default to VM runner target
  runner:
    build: .
    privileged: true
    tmpfs:
      - /tmp
      - /run
      - /scratch
    labels:
      # This allows the runner to re-launch itself in an ephemeral container
      io.balena.features.balena-socket: true
