#!/usr/bin/env bash

set -ae

# ping the docker daemon socket
curl --silent --fail --unix-socket /var/run/docker.sock http:/v1.41/_ping

# check for runner listener process
pgrep Runner.Listener

# print the runner agent id
jq -r '.agentId' .runner
