# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true

["mikefarah/yq"]
tag = "v4.30.7"
asset_filters = [".tar.gz"]
target = "/usr/local/bin/yq"
verify_sha256 = "5910801c24cf275b75768b0c05e95f2e3f25fcd0ed1172790bb9920f1b0f3477"
file = "yq_*"
all = false

["powershell/powershell"]
asset_filters = ["powershell", "^fxdependent", "^alpine", ".tar.gz"]
tag = "v7.3.2"
target = "/opt/microsoft/powershell/7"
verify_sha256 = "77700ff7160f77909ea5dccea0340caeb876f6e12d92d21c5fd7a79fcf377d1a"
file = "*"

["actions/runner"]
asset_filters = ["^noexternals", "^noruntime", ".tar.gz"]
tag = "v2.303.0"
target = "./"
verify_sha256 = "e4a9fb7269c1a156eb5d5369232d0cd62e06bec2fd2b321600e85ac914a9cc73"
file = "*"

["actions/runner-container-hooks"]
asset_filters = ["docker", ".zip"]
tag = "v0.3.1"
target = "./docker/"
verify_sha256 = "93e1f85b6986181e89c08c38605d11d2e3e37a990ad388e0401c872609bfcc69"
file = "*"

["https://nodejs.org/dist/v18.14.2/node-v18.14.2-linux-x64.tar.xz"]
target = "/usr/"
verify_sha256 = "de15b44738578367cfb250b6551b4c97e0e0e8050fa931a4a9a7262d374d6034"
file = "node-v18.14.2-linux-x64/*"
