name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  # allow external contributions to use secrets within trusted code
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      working_directory: runner
      repo_config: true
      repo_homepage: "https://docs.github.com/en/actions/hosting-your-own-runners"
      repo_description: "GitHub self-hosted runner images for common system architectures."
      docker_images: |
        ghcr.io/product-os/self-hosted-runners
      bake_targets: |
        default,focal
      token_scope: >-
          {
            "actions": "read",
            "administration": "write",
            "checks": "read",
            "contents": "write",
            "members": "read",
            "metadata": "read",
            "organization_secrets": "read",
            "organization_self_hosted_runners": "write",
            "packages": "write",
            "pages": "write",
            "pull_requests": "read",
            "secrets": "read",
            "statuses": "read",
            "workflows": "read"
          }
